server:
  port: 83
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos地址

#消费者将要去访问的微服务名称
service-url:
  nacos-user-service: http://nacos-payment-provider

logging:
  file: C:\\logs\\cloudalibaba-order-consumer83.log
