server:
  port: 3344

spring:
  application:
    name: cloud-config-center #配置中心dev
  cloud:
    config:
      server:
        git:
          uri: git@github.com:zzyybs/springcloud-config.git #github上面的git仓库名字
          search-paths:
            - springcloud-config
      label: master #master分支

eureka:
  client:
    #表示是否将自己注册进eurekaServer默认为true
    register-with-eureka: true
    #是否从eurekaServer抓取已有的注册信息,默认为true,单节点无所谓,集群必须设置为true才能配合Ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
