#下面这种配置不好的地方在于要写死
#spring:
#  application:
#    name: cloud-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: payment_route #payment_route #路由的ID，没有固定规则但要求唯一、建议配服务名
#          uri: http://localhost:8001       #匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/get/**       #断言,路径相匹配的进行路由
#
#        - id: payment_route2 #payment_route #路由的ID，没有固定规则但要求唯一、建议配服务名
#          uri: http://localhost:8001       #匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/lb/**          #断言,路径相匹配的进行路由, lb=loadBalance
#这种写法可以自动去寻找
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能,利用微服务名进行路由

      routes:
        - id: payment_route #payment_route #路由的ID，没有固定规则但要求唯一、建议配服务名
          #lb是指负载均衡,而非访问中的uri地址
          uri: lb://cloud-payment-service       #匹配后提供服务的路由地址
#          filters:
#            - AddRequestParamter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头加上一对请求头,名称为X-Request-Id值为1024
          predicates:
            - Path=/payment/get/**       #断言,路径相匹配的进行路由

        - id: payment_route2 #payment_route #路由的ID，没有固定规则但要求唯一、建议配服务名
          uri: lb://cloud-payment-service       #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**          #断言,路径相匹配的进行路由, lb=loadBalance
            #- After=2020-02-21T15:51:37.485+08:00[Asia/Shanghai]
            #- Cookie=username,zzyy
            #- Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性并且为整数的正则表达式
            #- Mehtod=GET
            #- Query=username, \d+ #要有参数名username并且值还要是整数才能路由
eureka:
  instace:
    hostname: cloud-gateway-service
  client:
    #表示是否将自己注册进eurekaServer默认为true
    register-with-eureka: true
    #是否从eurekaServer抓取已有的注册信息,默认为true,单节点无所谓,集群必须设置为true才能配合Ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka

server:
  port: 9527

logging:
  file: C:\\logs\\cloud-gateway-service.log
