sharding:
  jdbc:
    datasource:
      names: m1,m2
      m1:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/edu_db_1?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8
        username: root
        password: root
      m2:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/edu_db_2?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8
        username: root
        password: root
    config:
      sharding:
        tables:
          course:
            key-generator:
              column: cid
              type: SNOWFLAKE
            actual-nodes: m$->{0..1}.course_$->{0..1}
            database-strategy:
              inline:
                sharding-column: user_id
                algorithm-expression: m$->{user_id % 2 + 1}
            table-strategy:
              inline:
                sharding-column: cid
                algorithm-expression: course_$->{cid % 2 + 1}
#        binding-tables: course  # 多个时逗号隔开
#        broadcast-tables: mc_master
#        master-slave-rules:
#          ms0:
#            master-data-source-name: master0
#            slave-data-source-names: master0salve0,master0slave1
#          ms1:
#            master-data-source-name: master1
#            slave-data-source-names: master1slave0,master1slave1
      props:
        sql:
          show: true