server:
  port: 8080
  servlet:
    session:
      timneout: 3000

spring:
  application:
    name: SpringSessionRedis
  redis:
    host: localhost
    port: 6379
    timeout: 3000
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: 1
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: 'spring:session'
